---
- name: Converge
  hosts: all
  vars:
    dns_port: 5353
  roles:
    - role: genlab.ufw
      disable_ipv6: true
      rules:
        - rule: allow
          # proto: udp
          port: "{{ dns_port }}"
          interface: lo
          direction: in
          comment: "Allow dnsmasq to serve DNS queries on the given interface"

    - role: genlab.dnsmasq
      iface: lo
      domain: adm.vpn
      nodes:
        - name: hub
          ip: 127.0.0.1
          port: "{{ dns_port }}"
